
[target.x86_64-unknown-linux-gnu]
pre-build = ["apt-get update && apt -y install pkg-config libfreetype6-dev libfontconfig1-dev mingw-w64 && export PKG_CONFIG_PATH=/usr/local/lib/x86_64-linux-gnu/pkgconfig && export PKG_CONFIG_SYSROOT_DIR=/usr/x86_64-w64-mingw32"]